name: Dutch gas prices
version: 2023.4.26.1
slug: dutch_gas_prices
description: Get gas prices from dutch gas stations
url: https://github.com/Skons/hassio-addons/tree/main/dutch_gas_prices
arch:
  - aarch64
  - amd64
  - armv7
  - i386
homeassistant_api: true
init: false
startup: services
hassio_role: default
services:
 - mqtt:want
options:
  log_level: info
  ocr:
    contrast_enhance: 2
schema:
  log_level: list(critical|error|warning|info|debug)
  mqtt_host: str?
  mqtt_port: int?
  mqtt_username: str?
  mqtt_password: str?
  ocr:
    contrast_enhance: int?

